version: '3'
services:
  nginx:
    build:
      context: ./docker/nginx/
    ports:
      - "8082:80"
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - node-service

  node-service:
    build:
      context: ./docker/nginx
    ports:
      - "8081:80"
    environment:
      - DB_HOST=db
      - DB_USER=root
      - DB_PASS=s1mpl3
    volumes:
      - .:/usr/src/app
    depends_on:
      - db

  db:
    build:
      context: .
      dockerfile: docker/db/Dockerfile
    restart: always
    ports:
    - "23306:3306"
    volumes:
      - "./_data_/db:/var/lib/mysql:Z"
    environment:
      MYSQL_ROOT_PASSWORD: s1mpl3
      MYSQL_DATABASE: books
      MYSQL_USER: root
      MYSQL_PASSWORD: s1mpl3
      MYSQL_HOST: localhost

volumes:
  db_data:
