version: '3'
services:
  nginx:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - node-service

  node-service:
    build: .
    environment:
      - DB_HOST=db
      - DB_USER=root
      - DB_PASS=s1mpl3
    volumes:
      - .:/usr/src/app
    depends_on:
      - db

  db:
    image: mysql:5.7
    environment:
      - MYSQL_DATABASE=books
      - MYSQL_ROOT_PASSWORD=s1mpl3
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
