# Use the official Nginx image as base
FROM nginx

# Copy the content of the public folder to Nginx default serving directory
COPY ./ /usr/share/nginx/html

# Expose port 80 to allow external access
EXPOSE 80
