version: '3'
services:
  db:
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypassword
      MYSQL_HOST: db
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - app-network

  node-service:
    build: ./docker/nginx/
    environment:
      DB_ROOT_PASSWORD: rootpassword
      DB_DATABASE: mydatabase
      DB_USERNAME: myuser
      DB_PASSWORD: mypassword
      DB_HOST: db
    depends_on:
      - db
    networks:
      - app-network

  nginx:
    image: nginx:latest
    ports:
      - "8085:80"
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - node-service
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  db_data:
